// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function Clean(arg1) {
  return window['go']['main']['App']['Clean'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetReceipt(arg1) {
  return window['go']['main']['App']['GetReceipt'](arg1);
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetStrings() {
  return window['go']['main']['App']['GetStrings']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}
