// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel():Promise<void>;

export function Clean(arg1:Array<string>):Promise<void>;

export function GetHistory(arg1:number):Promise<Array<Record<string, any>>>;

export function GetReceipt(arg1:string):Promise<Record<string, any>>;

export function GetRules():Promise<string>;

export function GetStrings():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function Scan(arg1:Array<string>):Promise<void>;
